version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/bash -c "cd /etc/nginx/ && mkdir sites-enabled && cd sites-enabled && ln -s ../sites-available/checkorphan.conf . && nginx -g 'daemon off;'"